=== sumnima-adhikari/assignment/xml labreport/number17.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="sales">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="salesman" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first" type="xs:string"/>
                    <xs:element name="middle" type="xs:string" minOccurs="0"/>
                    <xs:element name="last" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="title" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="phone">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:integer">
                      <xs:attribute name="type" default="personal">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="personal"/>
                            <xs:enumeration value="work"/>
                            <xs:enumeration value="home"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="area" type="xs:string"/>
              <xs:element name="records">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="product">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="sku" type="xs:string"/>
                          <xs:element name="productName" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  <xs:element name="quantity" type="xs:integer"/>
                    <xs:element name="price">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:decimal">
                            <xs:attribute name="currency" default="NPR">
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:enumeration value="INR"/>
                                  <xs:enumeration value="NPR"/>
                                  <xs:enumeration value="USD"/>
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element> 
                    <xs:element name="date">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="type">
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:enumeration value="AD"/>
                                  <xs:enumeration value="BS"/>
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element> </xs:sequence>
          </xs:complexType>
        </xs:element> </xs:sequence>
    </xs:complexType>
  </xs:element> 
  </xs:schema>

=== sumnima-adhikari/assignment/xml labreport/number17.xml
<?xml version="1.0" encoding="UTF-8"?>
<sales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/sherpa%20trade%20ilam/Desktop/xml%20labreport/number17.xsd">
<salesman>
<name title="person">
<first>Ram</first>
<middle>Bahadur</middle>
<last>Thapa</last>
</name>
<phone type="personal">9823456683</phone>
<area>Kathmandu</area>
<records>
<record>
<product id="p101">
<sku>gurde</sku>
<product_name>Scrub</product_name>
</product>
<quantity>12</quantity>
<price currency="NPR">350</price> 
<date type="BS">2082-10-10</date> 
</record>
<record>
<product id="102">
<sku>Rode</sku>
<product_name>Lip Gloss</product_name>
</product>
<quantity>40</quantity>
<price currency="INR">50</price>
<date type="AD">2027-01-01</date>
</record>
</records>
</salesman>
<salesman>
<name title="person2">
<first>Rita</first>
<last>Rai</last>
</name>
<phone type="work">9534875387</phone>
<area>Bhaktapur</area>
<records>
<record>
<product id="p103">
<sku>Yuki</sku>
<productName>Eyeliner</productName>
</product>
<quantity>20</quantity>
<price currency="INR">300</price>
<date type="BS">2082-03-19</date>
</record>
</records>
</salesman>
</sales>
