=== sumnima-adhikari/assignment/xml labreport/number6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="university">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="school">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="location" type="xs:string"/>
                            <xs:element name="staffCollection">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="staff" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="title" type="xs:string" minOccurs="0"/>
                                                    <xs:element name="category">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="academic"/>
                                                                <xs:enumeration value="general"/>
                                                                <xs:enumeration value="technical"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="address" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="street" type="xs:string"/>
                                                                <xs:element name="suburb" type="xs:string"/>
                                                                <xs:element name="postcode" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="stId" type="xs:ID" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="subjectCollection">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="subject" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="description" type="xs:string"/>
                                                    <xs:element name="capacity">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minInclusive value="40"/>
                                                                <xs:maxInclusive value="60"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="taughtBy">
                                                        <xs:complexType>
                                                            <xs:attribute name="staffRef" type="xs:IDREF" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="subId" type="xs:ID" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="sid" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sumnima-adhikari/assignment/xml labreport/number6.xml
<?xml version="1.0" encoding="UTF-8"?>
<university xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/sherpa%20trade%20ilam/Desktop/xml%20labreport/number6.xsd">
    <school sid="s1">
        <name>Green Valley Academy</name>
        <location>Malapath</location>
        <staffCollection>
            <staff stId="st8">
                <name>Chintamani</name>
                <category>general</category>
                <address>
                    <street>Main street</street>
                    <suburb>Narayansthan</suburb>
                    <postcode>55770</postcode>
                </address>
                <address>
                    <street>23 Zero Road</street>
                    <suburb>Zero</suburb>
                    <postcode>43699</postcode>
                </address>
            </staff>
            <staff stId="st00">
                <name>Manku Shrestha</name>
                <title>Professor</title>
                <category>academic</category>
                <address>
                    <street>2nd street</street>
                    <suburb>Naya Bazar</suburb>
                    <postcode>33600</postcode>
                </address>
            </staff>
            <staff stId="st01">
                <name>Michael Gurung</name>
                <title>Lab Professor</title>
                <category>technical</category>
                <address>
                    <street>West street</street>
                    <suburb>Bhanudhoka</suburb>
                    <postcode>24600</postcode>
                </address>
            </staff>
        </staffCollection>
        <subjectCollection>
            <subject subId="sub6">
                <name>Web Technology</name>
                <description>HTML and CSS</description>
                <capacity>60</capacity>
                <taughtBy staffRef="st00"/>
            </subject>
            <subject subId="sub8">
                <name>Science</name>
                <description>Human Anatomy</description>
                <capacity>40</capacity>
                <taughtBy staffRef="st01"/>
            </subject>
        </subjectCollection>
    </school>
</university>
