=== sumnima-adhikari/assignment/xml labreport/number13.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="hospital">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="patient" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first" type="xs:string"/>
                    <xs:element name="middle" type="xs:string"/>
                    <xs:element name="Last" type="xs:string"/> </xs:sequence> 
                </xs:complexType>
              </xs:element>
              <xs:element name="patientNumber">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:pattern value="\d{5}"/> </xs:restriction>
                </xs:simpleType> 
              </xs:element>
              <xs:element name="doctorname" type="xs:string"/>
              <xs:element name="disease" type="xs:string" maxOccurs="unbounded"/>
              <xs:element name="consultationCharge">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="500"/>
                    <xs:maxInclusive value="5000"/>
                  </xs:restriction>
                </xs:simpleType>  
              </xs:element>
              <xs:element name="labTests">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="test" type="xs:string" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element> </xs:sequence>
    </xs:complexType>
  </xs:element> </xs:schema>

=== sumnima-adhikari/assignment/xml labreport/number13.xml
<?xml version="1.0" encoding="UTF-8"?>
<hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/sherpa%20trade%20ilam/Desktop/xml%20labreport/number13.xsd">
<patient>
<name>
<first>Mary</first>
<middle>Elasia</middle>
<Last>Warner</Last>
</name>
<patientNumber>12300</patientNumber>
<doctorname>Dr.Archie</doctorname>
<disease>Hypertension</disease>
<disease>Stones</disease>
<consultationCharge>2000</consultationCharge>
<labTests>
<test>CT scan</test>
<test>Urine Analysis</test>
<test>Blood Sugar Level</test>
</labTests>
</patient>
</hospital>
