=== sumnima-adhikari/assignment/xml labreport/number4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="first_name" type="xs:string"/>
                                        <xs:element name="middle_name" type="xs:string"/>
                                        <xs:element name="last_name" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="title" default="mr">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="mr"/>
                                                <xs:enumeration value="ms"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="phone" type="xs:string"/>
                                    <xs:attribute name="email" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="page_no" type="xs:integer"/>
                            <xs:element name="price">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="currency" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="ISBN" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sumnima-adhikari/assignment/xml labreport/number4.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/sherpa%20trade%20ilam/Desktop/xml%20labreport/number4.xsd">
<book ISBN="n234">
<title>Web development</title>
<author title="mr" phone="9854678443" email="suren@gmail.com">
<first_name>Suren</first_name>
<middle_name>Kumar</middle_name>
<last_name>Rai</last_name>
</author>
<author title="ms" phone="9854989894" email="menuka@gmail.com">
<first_name>Menuka</first_name>
<middle_name>Maya</middle_name>
<last_name>Basnet</last_name>
</author>
<author title="mr" phone="9884934566" email="arun@gmail.com">
<first_name>Arun</first_name>
<middle_name>Bahadur</middle_name>
<last_name>Shrestha</last_name>
</author>
<page_no>445</page_no>
<price currency="NPR">550</price>
</book>
</books>
