=== sumnima-adhikari/assignment/xml labreport/number12.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="bib">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:choice>
                <xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
                <xs:element name="editor">
                  <xs:complexType mixed="true">
                    <xs:sequence>
                      <xs:element name="affiliation" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:choice>
              <xs:element name="publisher" type="xs:string"/>
              <xs:element name="price" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="year" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sumnima-adhikari/assignment/xml labreport/number12.xml
<?xml version="1.0" encoding="UTF-8"?>
<bib xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/sherpa%20trade%20ilam/Desktop/xml%20labreport/number12.xsd">
<book year="1994">
<title>TCP/IP Illustrated</title>
<author>Stevens</author>
<publisher>Addison-Wesley</publisher>
<price>65.95</price>
</book>
<book year="1994">
<title>Principles of Databases</title>
<author>Abiteboul</author>
<publisher>Addison-Wesley</publisher>
<price>35.89</price>
</book>
<book year="1992">
<title>Advanced Programming in the Unix environment</title>
<author>Stevens</author>
<publisher>Addison-Wesley</publisher>
<price>65.95</price>
</book>
<book year="2000">
<title>Data on the Web</title>
<author>Abiteboul</author>
<author>Buneman</author>
<author>Suciu</author>
<publisher>Morgan Kaufmann Publishers</publisher>
<price> 39.95</price>
</book>
<book year="1992">
<title>The Economics of Technology and Content for Digital TV</title>
<editor> Gerbarg <affiliation>CITI</affiliation> </editor>
<publisher>Kluwer Academic Publishers</publisher>
<price>129.95</price>
</book>
</bib>
