=== sumnima-adhikari/assignment/xml labreport/number3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="songs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="song" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="singer" type="xs:string"/>
                            <xs:element name="composer" type="xs:string"/>
                            <xs:element name="length" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== sumnima-adhikari/assignment/xml labreport/number3.xml
<?xml version="1.0" encoding="UTF-8"?>
<songs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/sherpa%20trade%20ilam/Desktop/xml%20labreport/number3.xsd"><song>
<name>Valentina</name>
<singer>Daniel Ceaser</singer>
<composer>Zachary Simmonds</composer>
<length>3</length>
</song>
<song>
<name>Normal Girl</name>
<singer>SZA</singer>
<composer>SZA</composer>
<length>5</length>
</song>
<song>
<name>Blank Space</name>
<singer>Taylor Swift</singer>
<composer> Taylor Swift</composer>
<length>5</length>
</song>
<song>
<name>Man Child</name>
<singer>Sabrina Carpenter</singer>
<composer>Amy Allen</composer>
<length>4</length>
</song>
</songs>
