=== sumnima-adhikari/assignment/xml labreport/number10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="booklist">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="author" type="xs:string"/>
              <xs:element name="publisher" type="xs:string"/>
              <xs:element name="edition" type="xs:integer"/>
              <xs:element name="price" type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sumnima-adhikari/assignment/xml labreport/number10.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href=""?>
<booklist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/sherpa%20trade%20ilam/Desktop/xml%20labreport/number10.xsd">
    <book>
        <title>Web Programming</title>
        <author>Chrisbates</author>
        <publisher>Wiley</publisher>
        <edition>3</edition>
        <price>300</price>
    </book>
    <book>
        <title>Internet world-wide-web</title>
        <author>Ditel</author>
        <publisher>Pearson</publisher>
        <edition>3</edition>
        <price>400</price>
    </book>
    <book>
        <title>Computer Networks</title>
        <author>Foruouzan</author>
        <publisher>Mc Graw Hill</publisher>
        <edition>5</edition>
        <price>700</price>
    </book>
    <book>
        <title>DBMS Concepts</title>
        <author>Navath</author>
        <publisher>Oxford</publisher>
        <edition>5</edition>
        <price>600</price>
    </book>
    <book>
        <title>Linux Programming</title>
        <author>Subhitab Das</author>
        <publisher>Oxford</publisher>
        <edition>8</edition>
        <price>300</price>
    </book>
</booklist>
